name: Deploy to Firebase
on:
  push:
    branches:
      - master # Or the branch you want to auto-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: firebase deploy --only hosting --token "$FIREBASE_TOKEN"
