name: Deploy to Firebase
on:
  push:
    branches:
      - master # Or the branch you want to auto-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build and Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          npm ci
          npm run build # Or your build command
          echo $FIREBASE_TOKEN | firebase login:ci --stdin
          firebase deploy --only hosting
